/**
 * Mock data for development
 * Will be replaced by Supabase queries in production
 */

export const categories = [
  { id: 'sweets', name: 'Sweets', slug: 'sweets', description: 'Traditional handcrafted sweets', image: '/images/full-brand-menu.jpeg', sort_order: 1 },
  { id: 'cakes', name: 'Cakes & Brownies', slug: 'cakes', description: 'Fresh brownies & Tres Leches cakes', image: '/images/handdrawn-menu.jpeg', sort_order: 2 },
  { id: 'brownies', name: 'Brownies', slug: 'brownies', description: 'Fudge & Red Velvet brownies', image: '/images/full-brand-menu.jpeg', sort_order: 3 },
  { id: 'desserts', name: 'Tres Leches & Puddings', slug: 'desserts', description: 'Artisan Tres Leches & tender coconut pudding', image: '/images/full-brand-menu.jpeg', sort_order: 4 },
  { id: 'drinks', name: 'Fresh Milkshakes', slug: 'drinks', description: 'Mango, Strawberry & Blueberry milk', image: '/images/handdrawn-menu.jpeg', sort_order: 5 },
  { id: 'gifting', name: 'Gifting & Catering', slug: 'gifting', description: 'Wedding, party & event catering', image: '/images/brand-hero-banner.jpeg', sort_order: 6 },
]

export const products = [
  {
    id: 'mutta-mittai',
    name: 'Muttā Mittai',
    slug: 'mutta-mittai',
    description: 'Our signature traditional sweet with a unique crunchy taste. Made fresh daily.',
    category_id: 'sweets',
    price: 190,
    image: '/images/items/mutta-mittai.jpg',
    is_available: true,
    is_trending: true,
    is_signature: true,
    sort_order: 1,
    variants: [
      { id: 'mm-50g', name: '50g cup', price: 50 },
      { id: 'mm-250', name: '250g', price: 190 },
      { id: 'mm-500', name: '500g', price: 350 },
    ],
  },
  {
    id: 'fudge-brownie',
    name: 'Fudge Brownie',
    slug: 'fudge-brownie',
    description: 'Rich, chocolaty & fudgy chocolate brownie slice. Sweetness in every bite.',
    category_id: 'brownies',
    price: 50,
    image: '/images/items/fudge-brownie.jpg',
    is_available: true,
    is_trending: true,
    is_signature: false,
    sort_order: 2,
    variants: [
      { id: 'fb-pc', name: 'Per piece', price: 50 },
    ],
  },
  {
    id: 'red-velvet-brownie',
    name: 'Red Velvet Brownie',
    slug: 'red-velvet-brownie',
    description: 'Decadent red velvet brownie with white chocolate swirl. Rich and delicious.',
    category_id: 'brownies',
    price: 70,
    image: '/images/items/red-velvet-brownie.jpg',
    is_available: true,
    is_trending: true,
    is_signature: false,
    sort_order: 3,
    variants: [
      { id: 'rvb-pc', name: 'Per piece', price: 70 },
    ],
  },
  {
    id: 'tres-leches-cake',
    name: 'Tres Leches Cake',
    slug: 'tres-leches-cake',
    description: 'Soft sponge cake soaked in three kinds of milk with fresh strawberry top.',
    category_id: 'desserts',
    price: 60,
    image: '/images/items/tres-leches-cake.jpg',
    is_available: true,
    is_trending: true,
    is_signature: true,
    sort_order: 4,
    variants: [
      { id: 'tlc-pc', name: 'Per piece', price: 60 },
    ],
  },
  {
    id: 'rasmali-tres-leches',
    name: 'Rsamalai Tres Leches',
    slug: 'rasmali-tres-leches',
    description: 'An indulgent fusion dessert soaked in three milks with cardamom and pistachios.',
    category_id: 'desserts',
    price: 120,
    image: '/images/items/rasmali-tres-leches.jpg',
    is_available: true,
    is_trending: true,
    is_signature: true,
    sort_order: 5,
    variants: [],
  },
  {
    id: 'lychee-tres-leches',
    name: 'Lychee Tres Leches',
    slug: 'lychee-tres-leches',
    description: 'Light and floral tres leches infused with fresh lychee cream.',
    category_id: 'desserts',
    price: 120,
    image: '/images/items/lychee-tres-leches.jpg',
    is_available: true,
    is_trending: false,
    is_signature: false,
    sort_order: 6,
    variants: [],
  },
  {
    id: 'blueberry-tres-leches',
    name: 'Blue Berry Tres Leches',
    slug: 'blueberry-tres-leches',
    description: 'Rich tres leches infused with fresh blueberry compote.',
    category_id: 'desserts',
    price: 120,
    image: '/images/items/blueberry-tres-leches.jpg',
    is_available: true,
    is_trending: false,
    is_signature: false,
    sort_order: 7,
    variants: [],
  },
  {
    id: 'tender-coconut-pudding',
    name: 'Tender Coconut Pudding',
    slug: 'tender-coconut-pudding',
    description: 'Creamy, fresh & refreshing tender coconut dessert cup. Pure bliss.',
    category_id: 'desserts',
    price: 60,
    image: '/images/items/tender-coconut-pudding.jpg',
    is_available: true,
    is_trending: true,
    is_signature: true,
    sort_order: 8,
    variants: [
      { id: 'tcp-cup', name: 'Per cup', price: 60 },
    ],
  },
  {
    id: 'mango-milk',
    name: 'Mango Milkshake',
    slug: 'mango-milk',
    description: 'Real Mango Real Happiness — classic thick mango milkshake.',
    category_id: 'drinks',
    price: 60,
    image: '/images/items/mango-milk.jpg',
    is_available: true,
    is_trending: false,
    is_signature: false,
    sort_order: 9,
    variants: [
      { id: 'mm-glass', name: 'Per glass', price: 60 },
    ],
  },
  {
    id: 'strawberry-milk',
    name: 'Strawberry Milkshake',
    slug: 'strawberry-milk',
    description: 'Classic creamy strawberry drink — refreshing and yummy.',
    category_id: 'drinks',
    price: 60,
    image: '/images/items/strawberry-milk.jpg',
    is_available: true,
    is_trending: false,
    is_signature: false,
    sort_order: 10,
    variants: [
      { id: 'sm-glass', name: 'Per glass', price: 60 },
    ],
  },
  {
    id: 'blueberry-milk',
    name: 'Blue Berry Milk',
    slug: 'blueberry-milk',
    description: 'Fresh & refreshing blueberry milk drink.',
    category_id: 'drinks',
    price: 40,
    image: '/images/items/juices-all.jpg',
    is_available: true,
    is_trending: false,
    is_signature: false,
    sort_order: 11,
    variants: [],
  },
]

export const occasions = [
  { id: 'birthday', name: 'Birthday', icon: '🎂', description: 'Make their day sweeter' },
  { id: 'wedding', name: 'Wedding', icon: '💍', description: 'Sweetness for your special day' },
  { id: 'anniversary', name: 'Anniversary', icon: '💝', description: 'Celebrate your journey' },
  { id: 'celebration', name: 'Celebration', icon: '🎉', description: 'Every moment deserves sweets' },
  { id: 'corporate', name: 'Corporate', icon: '🏢', description: 'Impress your team & clients' },
  { id: 'gifting', name: 'Gifting', icon: '🎁', description: 'Sweet gifts, sweet memories' },
]

export const businessSettings = {
  name: 'BLOODY Sweet by fafa',
  tagline: 'BAKERY • JUICES • SWEETS',
  phone: '8643839796',
  whatsapp: '918643839796',
  contactPerson: 'Saleem Basha (Revenue and Operation Manager)',
  email: 'orders@bloodysweetbyfafa.com',
  address: 'BLOODY Sweet by fafa, Orders Undertaken',
  city: '',
  openingHours: 'Mon–Sat: 10 AM – 9 PM',
  instagram: '@BLODYSWEET_BYFAFA',
  facebook: '',
  invoicePrefix: 'BS',
  quotePrefix: 'BQ',
  deliveryAvailable: true,
  pickupAvailable: true,
  footerMessage: 'Made fresh. Made to be remembered.',
}

// Demo orders for admin (Saleem Bhai & Akram Bhai)
export const demoOrders = [
  {
    id: 'ord-1',
    order_number: 'BS-2026-00001',
    customer_name: 'Saleem Bhai',
    customer_phone: '8643839796',
    delivery_type: 'delivery',
    address: 'Orders Undertaken Office, Main Road',
    requested_date: '2026-09-25',
    notes: 'Signature Sweet Box & Brownie Pack',
    status: 'confirmed',
    payment_status: 'paid',
    items: [
      { product_name: 'Muttā Mittai', variant_name: '500g', quantity: 2, unit_price: 350 },
      { product_name: 'Fudge Brownie', variant_name: 'Per piece', quantity: 4, unit_price: 50 },
    ],
    subtotal: 900,
    delivery_fee: 50,
    total: 950,
    created_at: '2026-09-24T10:30:00+05:30',
  },
  {
    id: 'ord-2',
    order_number: 'BS-2026-00002',
    customer_name: 'Akram Bhai',
    customer_phone: '8643839796',
    delivery_type: 'pickup',
    address: '',
    requested_date: '2026-09-24',
    notes: 'Tres Leches Special Party Order',
    status: 'preparing',
    payment_status: 'paid',
    items: [
      { product_name: 'Rsamalai Tres Leches', variant_name: null, quantity: 5, unit_price: 120 },
      { product_name: 'Tender Coconut Pudding', variant_name: 'Per cup', quantity: 4, unit_price: 60 },
    ],
    subtotal: 840,
    delivery_fee: 0,
    total: 840,
    created_at: '2026-09-24T09:15:00+05:30',
  },
]

export const demoQuotes = [
  {
    id: 'qt-1',
    quote_number: 'BQ-2026-00001',
    customer_name: 'Saleem Bhai',
    customer_phone: '8643839796',
    customer_email: 'saleem@bloodysweetbyfafa.com',
    request_type: 'wedding',
    event_date: '2026-12-15',
    quantity: '200 guests',
    budget: '₹25,000 – ₹40,000',
    requirements: 'Traditional Indian sweets assortment for wedding reception. Mix of Muttā Mittai variations, brownies, and custom desserts.',
    message: 'We want something very premium and memorable for our guests.',
    status: 'new',
    quoted_amount: null,
    owner_notes: '',
    created_at: '2026-09-23T16:00:00+05:30',
  },
  {
    id: 'qt-2',
    quote_number: 'BQ-2026-00002',
    customer_name: 'Akram Bhai',
    customer_phone: '8643839796',
    customer_email: 'akram@bloodysweetbyfafa.com',
    request_type: 'corporate',
    event_date: '2026-10-05',
    quantity: '50 boxes',
    budget: '₹15,000 – ₹20,000',
    requirements: 'Diwali corporate gift boxes. Each box should contain assorted sweets and brownies.',
    message: 'Need branded packaging if possible.',
    status: 'contacted',
    quoted_amount: 18000,
    owner_notes: 'Discussed over call. Will create custom boxes.',
    created_at: '2026-09-22T11:30:00+05:30',
  },
]

export const demoExpenses = [
  { id: 'exp-1', category: 'Ingredients', amount: 4500, date: '2026-09-24', payment_method: 'cash', description: 'Milk, sugar, ghee, dry fruits', created_at: '2026-09-24T08:00:00+05:30' },
  { id: 'exp-2', category: 'Packaging', amount: 1200, date: '2026-09-23', payment_method: 'upi', description: 'Sweet boxes, brownie wrappers', created_at: '2026-09-23T10:30:00+05:30' },
  { id: 'exp-3', category: 'Delivery', amount: 300, date: '2026-09-24', payment_method: 'cash', description: 'Delivery charges', created_at: '2026-09-24T12:00:00+05:30' },
  { id: 'exp-4', category: 'Electricity', amount: 3500, date: '2026-09-20', payment_method: 'upi', description: 'Monthly electricity bill', created_at: '2026-09-20T09:00:00+05:30' },
]

export const demoStock = [
  { id: 'stk-1', name: 'Milk', current_stock: 6, unit: 'L', min_level: 10, status: 'low' },
  { id: 'stk-2', name: 'Sugar', current_stock: 15, unit: 'kg', min_level: 5, status: 'ok' },
  { id: 'stk-3', name: 'Ghee', current_stock: 3, unit: 'kg', min_level: 2, status: 'ok' },
  { id: 'stk-4', name: 'All-Purpose Flour', current_stock: 8, unit: 'kg', min_level: 5, status: 'ok' },
  { id: 'stk-5', name: 'Cocoa Powder', current_stock: 0.5, unit: 'kg', min_level: 1, status: 'low' },
  { id: 'stk-6', name: 'Cream Cheese', current_stock: 2, unit: 'kg', min_level: 1, status: 'ok' },
  { id: 'stk-7', name: 'Dark Chocolate', current_stock: 1, unit: 'kg', min_level: 2, status: 'low' },
  { id: 'stk-8', name: 'Pistachios', current_stock: 0.8, unit: 'kg', min_level: 0.5, status: 'ok' },
]
